# Generated by Django 5.0.6 on 2024-06-26 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jefe_proceso',
            name='proceso',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.proceso'),
        ),
    ]
